IMPLICATION_MAP: dict[str, list[str]] = {
    "next.js": ["react", "react.js", "javascript", "html", "css", "frontend", "server-side rendering", "ssr"],
    "nuxt.js": ["vue", "vue.js", "javascript", "html", "css", "frontend", "ssr"],
    "gatsby": ["react", "react.js", "javascript", "graphql", "frontend"],
    "remix": ["react", "react.js", "javascript", "frontend"],
    "sveltekit": ["svelte", "javascript", "frontend"],
    "fastapi": ["python", "rest api", "restful", "async", "backend", "pydantic"],
    "django": ["python", "oop", "mvc", "backend", "rest api", "orm"],
    "django rest framework": ["django", "python", "rest api", "backend"],
    "flask": ["python", "rest api", "backend"],
    "express": ["node.js", "javascript", "rest api", "backend"],
    "express.js": ["node.js", "javascript", "rest api", "backend"],
    "nestjs": ["node.js", "typescript", "rest api", "backend"],
    "spring boot": ["java", "rest api", "backend", "microservices"],
    "spring": ["java", "backend"],
    "rails": ["ruby", "rest api", "backend", "mvc"],
    "ruby on rails": ["ruby", "rest api", "backend", "mvc"],
    "laravel": ["php", "rest api", "backend", "mvc"],
    "asp.net": ["c#", ".net", "backend"],
    "react native": ["react", "javascript", "mobile development"],
    "flutter": ["dart", "mobile development"],
    "ionic": ["angular", "typescript", "mobile development"],
    "electron": ["javascript", "node.js", "desktop development"],
    "tensorflow": ["python", "machine learning", "deep learning", "ai"],
    "pytorch": ["python", "machine learning", "deep learning", "ai"],
    "keras": ["python", "deep learning", "tensorflow"],
    "scikit-learn": ["python", "machine learning"],
    "pandas": ["python", "data analysis"],
    "numpy": ["python", "data analysis"],
    "langchain": ["python", "llm", "ai", "rag"],
    "openai api": ["ai", "llm", "api integration"],
    "hugging face": ["python", "machine learning", "nlp", "transformers"],
    "docker": ["containerization", "devops"],
    "kubernetes": ["docker", "containerization", "devops", "orchestration", "k8s"],
    "terraform": ["infrastructure as code", "devops", "cloud"],
    "ansible": ["devops", "automation", "configuration management"],
    "jenkins": ["ci/cd", "devops", "automation"],
    "github actions": ["ci/cd", "devops", "automation"],
    "gitlab ci": ["ci/cd", "devops", "automation"],
    "aws": ["cloud", "cloud computing"],
    "azure": ["cloud", "cloud computing"],
    "gcp": ["cloud", "cloud computing"],
    "postgresql": ["sql", "database", "relational database"],
    "mysql": ["sql", "database", "relational database"],
    "sqlite": ["sql", "database"],
    "mongodb": ["nosql", "database"],
    "redis": ["caching", "database", "in-memory"],
    "elasticsearch": ["search", "nosql", "database"],
    "dynamodb": ["nosql", "database", "aws"],
    "firebase": ["backend", "nosql", "google cloud"],
    "supabase": ["backend", "postgresql", "database"],
    "prisma": ["orm", "database", "typescript"],
    "sequelize": ["orm", "database", "javascript"],
    "sqlalchemy": ["orm", "database", "python"],
    "mongoose": ["orm", "mongodb", "javascript"],
    "graphql": ["api", "query language"],
    "apollo": ["graphql", "api"],
    "webpack": ["javascript", "build tools", "frontend"],
    "vite": ["javascript", "build tools", "frontend"],
    "babel": ["javascript", "transpiler"],
    "eslint": ["javascript", "code quality"],
    "prettier": ["code formatting"],
    "jest": ["javascript", "testing", "unit testing"],
    "cypress": ["testing", "e2e testing", "frontend"],
    "playwright": ["testing", "e2e testing"],
    "selenium": ["testing", "e2e testing", "automation"],
    "pytest": ["python", "testing", "unit testing"],
    "redux": ["react", "state management", "javascript"],
    "zustand": ["react", "state management"],
    "mobx": ["state management", "javascript"],
    "tailwind css": ["css", "frontend", "responsive design"],
    "bootstrap": ["css", "frontend", "responsive design"],
    "material ui": ["react", "css", "frontend", "ui library"],
    "shadcn": ["react", "tailwind css", "frontend", "ui library"],
    "storybook": ["frontend", "ui development", "component library"],
    "figma": ["ui design", "ux design", "prototyping"],
    "git": ["version control"],
    "github": ["git", "version control", "collaboration"],
    "gitlab": ["git", "version control", "ci/cd"],
    "jira": ["project management", "agile"],
    "confluence": ["documentation"],
    "slack": ["communication", "collaboration"],
    "vercel": ["deployment", "frontend", "serverless"],
    "netlify": ["deployment", "frontend"],
    "heroku": ["deployment", "paas"],
    "nginx": ["web server", "reverse proxy", "devops"],
    "apache kafka": ["event streaming", "messaging", "distributed systems"],
    "rabbitmq": ["messaging", "queue", "distributed systems"],
    "grpc": ["rpc", "api", "protocol buffers"],
    "spark": ["big data", "data processing", "distributed computing"],
    "hadoop": ["big data", "distributed computing"],
    "airflow": ["data engineering", "workflow orchestration", "python"],
    "dbt": ["data transformation", "sql", "data engineering"],
    "snowflake": ["data warehouse", "sql", "cloud"],
    "databricks": ["big data", "spark", "machine learning"],
    "power bi": ["data visualization", "business intelligence"],
    "tableau": ["data visualization", "business intelligence"],
    "d3.js": ["javascript", "data visualization", "frontend"],
    "three.js": ["javascript", "3d graphics", "webgl", "frontend"],
}


def get_implied_skills(existing_skills: set[str]) -> set[str]:
    implied = set()
    for skill in existing_skills:
        skill_lower = skill.lower().strip()
        if skill_lower in IMPLICATION_MAP:
            implied.update(IMPLICATION_MAP[skill_lower])
        for key, values in IMPLICATION_MAP.items():
            if skill_lower == key or skill_lower in [v.lower() for v in values]:
                implied.update(values)
    return implied
