VARIATIONS: dict[str, list[str]] = {
    "react": ["react", "react.js", "reactjs"],
    "node": ["node", "node.js", "nodejs"],
    "next": ["next", "next.js", "nextjs"],
    "vue": ["vue", "vue.js", "vuejs"],
    "angular": ["angular", "angularjs", "angular.js"],
    "typescript": ["typescript", "ts"],
    "javascript": ["javascript", "js", "es6", "es2015", "ecmascript"],
    "python": ["python", "python3", "py"],
    "java": ["java", "jdk"],
    "c#": ["c#", "csharp", "c sharp"],
    "c++": ["c++", "cpp", "cplusplus"],
    "go": ["go", "golang"],
    "rust": ["rust", "rustlang"],
    "ruby": ["ruby", "rb"],
    "php": ["php"],
    "swift": ["swift"],
    "kotlin": ["kotlin"],
    "postgresql": ["postgresql", "postgres", "psql", "pgsql"],
    "mysql": ["mysql", "my sql"],
    "mongodb": ["mongodb", "mongo"],
    "redis": ["redis"],
    "elasticsearch": ["elasticsearch", "elastic search", "elastic"],
    "kubernetes": ["kubernetes", "k8s"],
    "docker": ["docker", "containerization", "containers"],
    "ci/cd": ["ci/cd", "cicd", "ci cd", "continuous integration", "continuous deployment"],
    "oop": ["oop", "object-oriented", "object oriented programming"],
    "rest": ["rest", "restful", "rest api", "rest apis", "restful api"],
    "graphql": ["graphql", "graph ql"],
    "websocket": ["websocket", "websockets", "web socket"],
    "aws": ["aws", "amazon web services"],
    "azure": ["azure", "microsoft azure"],
    "gcp": ["gcp", "google cloud", "google cloud platform"],
    "machine learning": ["machine learning", "ml"],
    "deep learning": ["deep learning", "dl"],
    "nlp": ["nlp", "natural language processing"],
    "llm": ["llm", "large language model", "large language models"],
    "full-stack": ["full-stack", "full stack", "fullstack"],
    "front-end": ["front-end", "frontend", "front end"],
    "back-end": ["back-end", "backend", "back end"],
    "async": ["async", "asynchronous", "async/await"],
    "ui/ux": ["ui/ux", "ui ux", "uiux", "user interface", "user experience"],
    "html": ["html", "html5"],
    "css": ["css", "css3"],
    "sass": ["sass", "scss"],
    "tailwind": ["tailwind", "tailwindcss", "tailwind css"],
    "bootstrap": ["bootstrap"],
    "material ui": ["material ui", "mui", "material design"],
    "express": ["express", "express.js", "expressjs"],
    "django": ["django"],
    "flask": ["flask"],
    "fastapi": ["fastapi", "fast api"],
    "spring": ["spring", "spring boot", "springboot"],
    "rails": ["rails", "ruby on rails", "ror"],
    "terraform": ["terraform", "tf"],
    "ansible": ["ansible"],
    "jenkins": ["jenkins"],
    "github actions": ["github actions", "gh actions"],
    "git": ["git"],
    "github": ["github"],
    "gitlab": ["gitlab"],
    "bitbucket": ["bitbucket"],
    "jira": ["jira"],
    "agile": ["agile", "scrum", "kanban"],
    "microservices": ["microservices", "micro services", "micro-services"],
    "api": ["api", "apis"],
    "sql": ["sql", "structured query language"],
    "nosql": ["nosql", "no sql", "non-relational"],
    "linux": ["linux", "unix"],
    "bash": ["bash", "shell", "shell scripting"],
    "webpack": ["webpack"],
    "vite": ["vite"],
    "figma": ["figma"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "tensorflow": ["tensorflow", "tf"],
    "pytorch": ["pytorch", "torch"],
    "scikit-learn": ["scikit-learn", "sklearn", "scikit learn"],
    "langchain": ["langchain"],
    "openai": ["openai", "open ai"],
    "firebase": ["firebase"],
    "supabase": ["supabase"],
    "vercel": ["vercel"],
    "netlify": ["netlify"],
    "heroku": ["heroku"],
    "nginx": ["nginx"],
    "apache": ["apache"],
    "rabbitmq": ["rabbitmq", "rabbit mq"],
    "kafka": ["kafka", "apache kafka"],
    "grpc": ["grpc", "g-rpc"],
    "soap": ["soap"],
    "oauth": ["oauth", "oauth2", "oauth 2.0"],
    "jwt": ["jwt", "json web token", "json web tokens"],
    "redux": ["redux"],
    "zustand": ["zustand"],
    "mobx": ["mobx"],
    "jest": ["jest"],
    "cypress": ["cypress"],
    "selenium": ["selenium"],
    "playwright": ["playwright"],
    "storybook": ["storybook"],
    "d3": ["d3", "d3.js", "d3js"],
    "three.js": ["three.js", "threejs", "three js"],
    "react native": ["react native"],
    "flutter": ["flutter"],
    "ionic": ["ionic"],
    "electron": ["electron", "electron.js"],
    "svelte": ["svelte", "sveltekit"],
    "remix": ["remix"],
    "gatsby": ["gatsby"],
    "nuxt": ["nuxt", "nuxt.js", "nuxtjs"],
    "prisma": ["prisma"],
    "sequelize": ["sequelize"],
    "mongoose": ["mongoose"],
    "sqlalchemy": ["sqlalchemy", "sql alchemy"],
    "celery": ["celery"],
    "airflow": ["airflow", "apache airflow"],
    "spark": ["spark", "apache spark", "pyspark"],
    "hadoop": ["hadoop"],
    "snowflake": ["snowflake"],
    "databricks": ["databricks"],
    "power bi": ["power bi", "powerbi"],
    "tableau": ["tableau"],
}


def get_all_variations(keyword: str) -> list[str]:
    keyword_lower = keyword.lower().strip()
    for canonical, variations in VARIATIONS.items():
        if keyword_lower in [v.lower() for v in variations]:
            return variations
        if keyword_lower == canonical.lower():
            return variations
    return [keyword_lower]
